Repository Art1985ss/AuthDemo, pull requests merged in 2020-03, with the labels that each got.

#2 #1 rb zt major change
  src/main/java/com/auth/AuthDemo/AuthDemoApplication.java
  src/main/java/com/auth/AuthDemo/entity/Answer.java
  src/main/java/com/auth/AuthDemo/entity/Question.java
  src/main/java/com/auth/AuthDemo/entity/Test.java
  src/main/java/com/auth/AuthDemo/entity/User.java
  src/main/java/com/auth/AuthDemo/gui/QuestionCreation.java
  src/main/java/com/auth/AuthDemo/repository/QuestionRepository.java
  src/main/java/com/auth/AuthDemo/repository/TestRepository.java
  src/main/java/com/auth/AuthDemo/repository/UserRepository.java
  src/main/java/com/auth/AuthDemo/service/AuthService.java
  src/main/java/com/auth/AuthDemo/service/QuestionService.java
  src/main/java/com/auth/AuthDemo/service/Service_.java
  src/main/java/com/auth/AuthDemo/service/StudentService.java
  src/main/java/com/auth/AuthDemo/service/TestService.java
  src/main/java/com/auth/AuthDemo/web/MainPage.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V1__testDBsetup.sql
  src/main/resources/templates/test.html
Labels: good first issue

#3 Timer
  web/html/dist/easytimer.js
  web/html/dist/easytimer.min.js
  web/html/dist/examples.min.css
  web/html/dist/examples.min.js
  web/html/lib/easytimer/dist/easytimer.min.js
  web/html/quiz.html
  web/node_modules/easytimer.js/LICENSE.md
  web/node_modules/easytimer.js/MIGRATION.md
  web/node_modules/easytimer.js/README.md
  web/node_modules/easytimer.js/dist/easytimer.js
  web/node_modules/easytimer.js/dist/easytimer.min.js
  web/node_modules/easytimer.js/index.d.ts
  web/node_modules/easytimer.js/package.json
  web/node_modules/easytimer.js/rollup.config.examples.js
  web/node_modules/easytimer.js/src/easytimer/customEventPolyfill.js
  web/node_modules/easytimer.js/src/easytimer/easytimer.js
  web/node_modules/easytimer.js/src/easytimer/leftPadding.js
  web/node_modules/easytimer.js/src/easytimer/timeCounter.js
  web/package-lock.json
Labels: enhancement

#31 #13 qu86 services unit tests
  src/test/java/com/auth/AuthDemo/AuthDemoApplicationTests.java
  src/test/java/com/auth/AuthDemo/service/QuestionServiceTest.java
  src/test/java/com/auth/AuthDemo/service/StudentServiceTest.java
  src/test/java/com/auth/AuthDemo/service/TestServiceTest.java
Labels: unit tests
